[package]
name = "ovium"
version = "0.1.0"
authors = ["Samir Noir <samir@noir.im>"]
edition = "2018"

[dependencies]
log = "0.4"
ssh2 = "0.6"
serde_json = "1.0.44"
serde = { version = "1.0.104", features = ["derive"] }
simplelog = "^0.7.4"
getopts = "0.2"
crossbeam-utils = "0.7.2"
